
import SearchBar from '@/components/SearchBar'
import '../globals.css'
import Header from '@/components/Header'




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params:{locale} }) {
 
 
  return (
    <html lang={locale}>
      <body className='bg-gray-900'>  
      <main >
      {children}
      </main>
      </body>
    </html>
  )
}
