
import SearchBar from '@/components/SearchBar'
import '../globals.css'
import Header from '@/components/Header'
import { NextIntlClientProvider, useMessages } from 'next-intl'
import tr from "@/messages/tr.json"
import en from "@/messages/en.json"




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params:{locale} }) {
 
  let currentMessages = {};

  // Seçilen dile göre uygun dil mesajlarını belirleyin
  if (locale === 'tr') {
    currentMessages = tr;
  } else if (locale === 'en') {
    currentMessages = en;
  }
  return (
    <html lang={locale}>
      <body className='bg-gray-900'>  
      <NextIntlClientProvider locale={locale} messages={currentMessages} >
      {children}
      </NextIntlClientProvider>
      </body>
    </html>
  )
}
