
import SearchBar from '@/components/SearchBar'
import '../globals.css'
import Header from '@/components/Header'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params:{locale} }) {
  return (
    <html lang={locale}>
      <body className='flex h-screen bg-gray-900 false' >
      <header>
      <Header/>
      </header>
      <div className='flex flex-col flex-1  w-full'>
      <SearchBar/>
      <main className='h-full overflow-y-auto'>
      {children}
      </main>
      </div>
      </body>
    </html>
  )
}
